# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: ValidCertificadora.VIDaaSConnect
PackageVersion: 1.0.2
PackageLocale: pt-BR
Publisher: Valid Certificadora
PackageName: VIDaaS Connect
License: Freeware
ShortDescription: Instalador do VIDaaS Connect
ManifestType: defaultLocale
ManifestVersion: 1.4.0
